os: linux
dist: bionic

language: generic

compiler:
  - gcc

env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src
    - CI_ROS_DISTRO="melodic"
    - PKG_SRC=${CATKIN_WS_SRC}/jps_global_planner
    - JPS3D_WS=~/jps3d_ws
    - JPS3D_SRC=${JPS3D_WS}/src

before_install:
  # Add ROS key
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  # Prepare rosdep to install dependencies
  - sudo apt-get update -qq
  - sudo apt-get install -y python-rosdep
  - sudo rosdep init
  - rosdep update
  # Install ROS
  - sudo apt-get install -y ros-${CI_ROS_DISTRO}-ros-base
  # Install jps3d
  - mkdir -p $JPS3D_SRC && cd $JPS3D_SRC
  - git clone https://github.com/KumarRobotics/jps3d.git
  - source /opt/ros/${CI_ROS_DISTRO}/setup.bash; \
      catkin_make_isolated --install \
      -DCMAKE_BUILD_TYPE=Release \
      --install-space /opt/ros/${CI_ROS_DISTRO}

install:
  # Create workspace
  - mkdir -p $PKG_SRC
  # Add ONLY the package under integration to the workspace using a symlink
  - ln -s $TRAVIS_BUILD_DIR $PKG_SRC
  # Use rosdep to install all dependencies (including ROS itself)
  - cd $CATKIN_WS
  - rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO

script:
  - source /opt/ros/$CI_ROS_DISTRO/setup.bash
  - cd $CATKIN_WS
  # Build packages
  - catkin_make -DCMAKE_BUILD_TYPE=Release
  - source devel/setup.bash
  # Run tests
  - catkin_make run_tests && catkin_test_results
  # Lint package files
  - sudo apt-get install -y python-catkin-lint
  - catkin lint -W2 --strict --explain $PKG_SRC
  - catkin_make roslint